# Generated by Django 3.2 on 2021-04-15 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, validators=[django.core.validators.URLValidator()])),
                ('short_url', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()])),
                ('url_hash', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
    ]
